/**
 * TabbedForm – tabbed document form with sections, sidebar, activity, and connections.
 *
 * Always expects at least 1 tab (generated by buildTabs in utils). When no Tab Break
 * fields exist, a single "Details" tab wraps all fields with section breaks. When no
 * tab has show_dashboard=1, the ConnectionDashboard renders as a section at the top
 * of the first tab.
 */

"use client";

import { useCallback, useEffect, useMemo, useState } from "react";
import type { FrappeFieldMeta, TabConfig } from "../types";
import { buildTabs } from "../utils";
import { ConnectionDashboard } from "./ConnectionDashboard";
import { DocumentActivity } from "./DocumentActivity";
import { DocumentSidebar } from "./DocumentSidebar";
import { FormSection } from "./FormSection";

interface TabbedFormProps {
  schemaFields: FrappeFieldMeta[];
  form: Record<string, any>;
  docData?: any;
  doctype: string;
  isReadOnly: boolean;
  isNew: boolean;
  isLoadingDoc: boolean;
  onFieldChange: (value: any, fieldname?: string) => void;
  collapsedSections: Record<string, boolean>;
  onToggleSection: (fieldname: string) => void;
  metaConfig?: any;
  reloadData?: () => void;
  reloadDoc?: () => void;
}

export function TabbedForm({
  schemaFields,
  form,
  docData,
  doctype,
  isReadOnly,
  isNew,
  isLoadingDoc,
  onFieldChange,
  collapsedSections,
  onToggleSection,
  metaConfig,
  reloadData,
  reloadDoc,
}: TabbedFormProps) {
  const [tabs, setTabs] = useState<TabConfig[]>([]);
  const [selectedTab, setSelectedTab] = useState<TabConfig | null>(null);
  const [tabFields, setTabFields] = useState<any[]>([]);

  const effectiveReload = reloadData || (() => {});

  const setTabHash = useCallback((tab: TabConfig) => {
    const hash = tab.fieldname || tab.label?.toLowerCase() || "";
    window.history.replaceState(null, "", `#${hash}`);
  }, []);

  useEffect(() => {
    if (!schemaFields || schemaFields.length === 0) return;
    const built = buildTabs(schemaFields);
    setTabs(built);

    const hash = window.location.hash.replace("#", "");
    if (hash && built.length > 0) {
      const matchedTab = built.find(
        (t) => (t.fieldname || t.label?.toLowerCase()) === hash,
      );
      setSelectedTab(matchedTab || built[0]);
      if (!matchedTab) setTabHash(built[0]);
    } else if (built.length > 0) {
      setSelectedTab(built[0]);
      setTabHash(built[0]);
    }
  }, [schemaFields, setTabHash]);

  useEffect(() => {
    if (!selectedTab || !tabs.length) return;
    const found = tabs.find((t) => t.fieldname === selectedTab.fieldname);
    if (found) setTabFields(found.sections);
  }, [selectedTab, tabs]);

  const handleTabClick = (tab: TabConfig) => {
    setSelectedTab(tab);
    setTabHash(tab);
  };

  const visibleTabs = useMemo(() => {
    if (!isReadOnly || tabs.length === 0) return tabs;
    return tabs.filter((tab) => {
      if (tab.show_dashboard === 1) return true;
      return tab.sections.some((section) => {
        return section.columns.some((col) => {
          return col.fields.some((field) => {
            if (field.hidden) return false;
            const value = form[field.fieldname];
            return value !== undefined && value !== null && value !== "" && value !== 0 && value !== false;
          });
        });
      });
    });
  }, [tabs, isReadOnly, form]);

  useEffect(() => {
    if (isReadOnly && visibleTabs.length > 0 && selectedTab) {
      const stillVisible = visibleTabs.find((t) => t.fieldname === selectedTab.fieldname);
      if (!stillVisible) {
        setSelectedTab(visibleTabs[0]);
      }
    }
  }, [visibleTabs, selectedTab, isReadOnly]);

  const hasDashboardTab = useMemo(() => tabs.some((t) => t.show_dashboard === 1), [tabs]);

  if (isLoadingDoc && !isNew) {
    return (
      <div className="space-y-4">
        {Array.from({ length: 4 }).map((_, i) => (
          <div key={i} className="h-16 bg-muted animate-pulse rounded-lg" />
        ))}
      </div>
    );
  }

  const isFirstTab = tabs.indexOf(selectedTab!) === 0;
  const showConnectionSection = !isNew && isFirstTab && !hasDashboardTab && form?.name;
  const isDashboardTab = (selectedTab as any)?.show_dashboard === 1;
  const hasVisibleContent = visibleTabs.length > 0;

  if (isReadOnly && !hasVisibleContent) {
    return (
      <div className="flex flex-col lg:flex-row gap-0">
        <div className="flex-1 min-w-0 flex flex-col">
          <div className="flex-1 min-h-0 px-4 py-4">
            <div className="text-center py-12 text-muted-foreground text-sm">
              No data to display.
            </div>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex flex-col lg:flex-row gap-0">
      <div className="flex-1 min-w-0 flex flex-col">
        <div className="flex-shrink-0">
          <div className="relative flex items-center justify-between px-4 pt-2 bg-muted/30 border-b rounded-t-lg">
            <ul className="flex pt-2 gap-x-6 list-none bg-transparent">
              {visibleTabs.map((tab, index) => (
                <li key={tab.fieldname || index} className="cursor-pointer">
                  <button
                    onClick={() => handleTabClick(tab)}
                    className={`flex items-center font-medium text-sm pb-2 px-1 transition-colors ${
                      selectedTab?.fieldname === tab.fieldname
                        ? "border-b-2 border-primary text-primary"
                        : "text-muted-foreground hover:text-foreground border-b-2 border-transparent"
                    }`}
                  >
                    {tab.label}
                  </button>
                </li>
              ))}
            </ul>
          </div>
        </div>

        <div className="flex-1 min-h-0 px-4 py-4">
          <div className="flex flex-col gap-4">
            <div className="flex-1 min-w-0 flex flex-col">
              <div>
                {showConnectionSection && (
                  <div className="mb-4">
                    <ConnectionDashboard
                      doctype={doctype}
                      docname={form.name}
                      metaConfig={metaConfig}
                    />
                  </div>
                )}

                {isDashboardTab && !isNew && form?.name && (
                  <ConnectionDashboard
                    doctype={doctype}
                    docname={form.name}
                    metaConfig={metaConfig}
                  />
                )}

                {!isDashboardTab && (
                  tabFields.length === 0 ? (
                    <div className="text-center py-12 text-muted-foreground text-sm">
                      No fields configured for this doctype.
                    </div>
                  ) : (
                    tabFields.map((section: any, index: number) => (
                      <div key={section.fieldname || index} className="mb-4">
                        <FormSection
                          section={section}
                          form={form}
                          doctype={doctype}
                          isReadOnly={isReadOnly}
                          isNew={isNew}
                          onFieldChange={onFieldChange}
                          isCollapsed={
                            collapsedSections[section.fieldname] ??
                            section.collapsed
                          }
                          onToggleSection={onToggleSection}
                        />
                      </div>
                    ))
                  )
                )}
              </div>

              {!isNew && <DocumentActivity form={form} docData={docData} onReload={reloadDoc} />}
            </div>
          </div>
        </div>
      </div>

      {!isNew && (
        <DocumentSidebar
          form={form}
          docData={docData}
          metaConfig={metaConfig}
          reloadData={effectiveReload}
        />
      )}
    </div>
  );
}

export default TabbedForm;