/** Azure Property – modern SaaS blue with a teal highlight. */

import { createEstatePreset } from "./preset-factory";

export const azureProperty = createEstatePreset({
  label: "Azure Property",
  description: "Modern product and SaaS feel",
  light: {
    background: "#f8fafc",
    foreground: "#0f172a",
    card: "#ffffff",
    "card-foreground": "#0f172a",
    popover: "#ffffff",
    "popover-foreground": "#0f172a",
    primary: "#2563eb",
    "primary-foreground": "#ffffff",
    secondary: "#e8effd",
    "secondary-foreground": "#1e3a8a",
    muted: "#f1f5f9",
    "muted-foreground": "#64748b",
    accent: "#0f766e",
    "accent-foreground": "#ffffff",
    border: "#e2e8f0",
    input: "#e2e8f0",
    ring: "#0f766e",
    "chart-1": "#2563eb",
    "chart-2": "#0f766e",
    "chart-3": "#60a5fa",
    "chart-4": "#1e3a8a",
    "chart-5": "#64748b",
    sidebar: "#f5f8fe",
    "sidebar-foreground": "#1e3a8a",
    "sidebar-primary": "#2563eb",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e3edfc",
    "sidebar-accent-foreground": "#1e3a8a",
    "sidebar-border": "#e2e8f0",
    "sidebar-ring": "#0f766e",
  },
  dark: {
    background: "#0b1220",
    foreground: "#e6edf8",
    card: "#141c2b",
    "card-foreground": "#e6edf8",
    popover: "#182133",
    "popover-foreground": "#e6edf8",
    primary: "#60a5fa",
    "primary-foreground": "#172554",
    secondary: "#26364d",
    "secondary-foreground": "#dbeafe",
    muted: "#252a33",
    "muted-foreground": "#a8b2c1",
    accent: "#2dd4bf",
    "accent-foreground": "#042f2e",
    border: "#243044",
    input: "#243044",
    ring: "#2dd4bf",
    "chart-1": "#60a5fa",
    "chart-2": "#2dd4bf",
    "chart-3": "#93c5fd",
    "chart-4": "#1d4ed8",
    "chart-5": "#a8b2c1",
    sidebar: "#0f172a",
    "sidebar-foreground": "#dbeafe",
    "sidebar-primary": "#60a5fa",
    "sidebar-primary-foreground": "#172554",
    "sidebar-accent": "#26364d",
    "sidebar-accent-foreground": "#dbeafe",
    "sidebar-border": "#1e293b",
    "sidebar-ring": "#2dd4bf",
  },
});
