/** Cyber Lime – acid lime on charcoal, high contrast and modern. */

import { createEstatePreset } from "./preset-factory";

export const cyberLime = createEstatePreset({
  label: "Cyber Lime",
  description: "Acid lime on charcoal, high contrast",
  light: {
    background: "#f9faf5",
    foreground: "#14170c",
    card: "#ffffff",
    "card-foreground": "#14170c",
    popover: "#ffffff",
    "popover-foreground": "#14170c",
    primary: "#4d7c0f",
    "primary-foreground": "#ffffff",
    secondary: "#eef4dd",
    "secondary-foreground": "#3f6212",
    muted: "#f4f5ef",
    "muted-foreground": "#6b7059",
    accent: "#0f172a",
    "accent-foreground": "#f8fafc",
    border: "#e3e6d5",
    input: "#e3e6d5",
    ring: "#4d7c0f",
    "chart-1": "#4d7c0f",
    "chart-2": "#0f172a",
    "chart-3": "#a3e635",
    "chart-4": "#65a30d",
    "chart-5": "#6b7059",
    sidebar: "#f4f7ea",
    "sidebar-foreground": "#3f6212",
    "sidebar-primary": "#4d7c0f",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e9f0d5",
    "sidebar-accent-foreground": "#3f6212",
    "sidebar-border": "#e3e6d5",
    "sidebar-ring": "#4d7c0f",
  },
  dark: {
    background: "#0c0f07",
    foreground: "#f2f7e4",
    card: "#141a0e",
    "card-foreground": "#f2f7e4",
    popover: "#1a2112",
    "popover-foreground": "#f2f7e4",
    primary: "#a3e635",
    "primary-foreground": "#1a2e05",
    secondary: "#26331a",
    "secondary-foreground": "#ecfccb",
    muted: "#1b2313",
    "muted-foreground": "#a8b394",
    accent: "#fafafa",
    "accent-foreground": "#18181b",
    border: "#2b3a1e",
    input: "#2b3a1e",
    ring: "#a3e635",
    "chart-1": "#a3e635",
    "chart-2": "#fafafa",
    "chart-3": "#bef264",
    "chart-4": "#65a30d",
    "chart-5": "#a8b394",
    sidebar: "#10160b",
    "sidebar-foreground": "#ecfccb",
    "sidebar-primary": "#a3e635",
    "sidebar-primary-foreground": "#1a2e05",
    "sidebar-accent": "#26331a",
    "sidebar-accent-foreground": "#ecfccb",
    "sidebar-border": "#22301a",
    "sidebar-ring": "#a3e635",
  },
});
