/** Midnight Aurora – modern violet/cyan theme, tuned for dark mode first. */

import { createEstatePreset } from "./preset-factory";

export const midnightAurora = createEstatePreset({
  label: "Midnight Aurora",
  description: "Modern violet and cyan glow",
  light: {
    background: "#f7f7fb",
    foreground: "#16121f",
    card: "#ffffff",
    "card-foreground": "#16121f",
    popover: "#ffffff",
    "popover-foreground": "#16121f",
    primary: "#6d28d9",
    "primary-foreground": "#ffffff",
    secondary: "#eee9fb",
    "secondary-foreground": "#4c1d95",
    muted: "#f3f2f9",
    "muted-foreground": "#6b6880",
    accent: "#0891b2",
    "accent-foreground": "#ffffff",
    border: "#e4e2ef",
    input: "#e4e2ef",
    ring: "#6d28d9",
    "chart-1": "#6d28d9",
    "chart-2": "#0891b2",
    "chart-3": "#a78bfa",
    "chart-4": "#22d3ee",
    "chart-5": "#6b6880",
    sidebar: "#f4f2fb",
    "sidebar-foreground": "#4c1d95",
    "sidebar-primary": "#6d28d9",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#eae4fa",
    "sidebar-accent-foreground": "#4c1d95",
    "sidebar-border": "#e4e2ef",
    "sidebar-ring": "#0891b2",
  },
  dark: {
    background: "#0b0a14",
    foreground: "#edeaf7",
    card: "#151327",
    "card-foreground": "#edeaf7",
    popover: "#1a1730",
    "popover-foreground": "#edeaf7",
    primary: "#a78bfa",
    "primary-foreground": "#1b0f3a",
    secondary: "#2a2440",
    "secondary-foreground": "#ddd6fe",
    muted: "#232035",
    "muted-foreground": "#a5a1bb",
    accent: "#22d3ee",
    "accent-foreground": "#06303a",
    border: "#2b2745",
    input: "#2b2745",
    ring: "#22d3ee",
    "chart-1": "#a78bfa",
    "chart-2": "#22d3ee",
    "chart-3": "#c4b5fd",
    "chart-4": "#0891b2",
    "chart-5": "#a5a1bb",
    sidebar: "#0f0d1c",
    "sidebar-foreground": "#ddd6fe",
    "sidebar-primary": "#a78bfa",
    "sidebar-primary-foreground": "#1b0f3a",
    "sidebar-accent": "#2a2440",
    "sidebar-accent-foreground": "#ddd6fe",
    "sidebar-border": "#221f38",
    "sidebar-ring": "#22d3ee",
  },
});
