/** Nairobi Slate – subtle East African property feel: deep blue and earth gold. */

import { createEstatePreset } from "./preset-factory";

export const nairobiSlate = createEstatePreset({
  label: "Nairobi Slate",
  description: "Local, professional real-estate feel",
  light: {
    background: "#f8fafb",
    foreground: "#101f2e",
    card: "#ffffff",
    "card-foreground": "#101f2e",
    popover: "#ffffff",
    "popover-foreground": "#101f2e",
    primary: "#19324d",
    "primary-foreground": "#ffffff",
    secondary: "#e9eef2",
    "secondary-foreground": "#19324d",
    muted: "#f2f4f5",
    "muted-foreground": "#66727d",
    accent: "#b68a3c",
    "accent-foreground": "#ffffff",
    border: "#e1e8ed",
    input: "#e1e8ed",
    ring: "#b68a3c",
    "chart-1": "#19324d",
    "chart-2": "#b68a3c",
    "chart-3": "#3b7ea1",
    "chart-4": "#0f766e",
    "chart-5": "#66727d",
    sidebar: "#f5f8fa",
    "sidebar-foreground": "#19324d",
    "sidebar-primary": "#19324d",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#e6edf2",
    "sidebar-accent-foreground": "#19324d",
    "sidebar-border": "#e1e8ed",
    "sidebar-ring": "#b68a3c",
  },
  dark: {
    background: "#0c1218",
    foreground: "#e3eaf1",
    card: "#141c24",
    "card-foreground": "#e3eaf1",
    popover: "#18212b",
    "popover-foreground": "#e3eaf1",
    primary: "#5b9bd5",
    "primary-foreground": "#10243a",
    secondary: "#293746",
    "secondary-foreground": "#dce6ef",
    muted: "#252b31",
    "muted-foreground": "#a6b0b8",
    accent: "#d1a94a",
    "accent-foreground": "#261d08",
    border: "#26333f",
    input: "#26333f",
    ring: "#d1a94a",
    "chart-1": "#5b9bd5",
    "chart-2": "#d1a94a",
    "chart-3": "#7fb2e0",
    "chart-4": "#2dd4bf",
    "chart-5": "#a6b0b8",
    sidebar: "#101822",
    "sidebar-foreground": "#dce6ef",
    "sidebar-primary": "#5b9bd5",
    "sidebar-primary-foreground": "#10243a",
    "sidebar-accent": "#293746",
    "sidebar-accent-foreground": "#dce6ef",
    "sidebar-border": "#1f2a36",
    "sidebar-ring": "#d1a94a",
  },
});
