/** Rose Quartz – modern rose and violet, softly rounded. */

import { createEstatePreset } from "./preset-factory";

export const roseQuartz = createEstatePreset({
  label: "Rose Quartz",
  description: "Modern rose with violet highlights",
  light: {
    radius: "0.75rem",
    background: "#fdf7f8",
    foreground: "#2a1721",
    card: "#ffffff",
    "card-foreground": "#2a1721",
    popover: "#ffffff",
    "popover-foreground": "#2a1721",
    primary: "#be123c",
    "primary-foreground": "#ffffff",
    secondary: "#fbe9ee",
    "secondary-foreground": "#881337",
    muted: "#f7f2f3",
    "muted-foreground": "#7a6a70",
    accent: "#7c3aed",
    "accent-foreground": "#ffffff",
    border: "#f0dfe4",
    input: "#f0dfe4",
    ring: "#7c3aed",
    "chart-1": "#be123c",
    "chart-2": "#7c3aed",
    "chart-3": "#f472b6",
    "chart-4": "#a21caf",
    "chart-5": "#7a6a70",
    sidebar: "#fbf3f5",
    "sidebar-foreground": "#881337",
    "sidebar-primary": "#be123c",
    "sidebar-primary-foreground": "#ffffff",
    "sidebar-accent": "#f8e3e9",
    "sidebar-accent-foreground": "#881337",
    "sidebar-border": "#f0dfe4",
    "sidebar-ring": "#7c3aed",
  },
  dark: {
    radius: "0.75rem",
    background: "#141014",
    foreground: "#f7ecf0",
    card: "#1e1720",
    "card-foreground": "#f7ecf0",
    popover: "#241c27",
    "popover-foreground": "#f7ecf0",
    primary: "#fb7185",
    "primary-foreground": "#4c0519",
    secondary: "#382631",
    "secondary-foreground": "#fecdd3",
    muted: "#2a2029",
    "muted-foreground": "#b8a5ad",
    accent: "#a78bfa",
    "accent-foreground": "#1e1b4b",
    border: "#3a2b36",
    input: "#3a2b36",
    ring: "#a78bfa",
    "chart-1": "#fb7185",
    "chart-2": "#a78bfa",
    "chart-3": "#f9a8d4",
    "chart-4": "#c084fc",
    "chart-5": "#b8a5ad",
    sidebar: "#191318",
    "sidebar-foreground": "#fecdd3",
    "sidebar-primary": "#fb7185",
    "sidebar-primary-foreground": "#4c0519",
    "sidebar-accent": "#382631",
    "sidebar-accent-foreground": "#fecdd3",
    "sidebar-border": "#2e2429",
    "sidebar-ring": "#a78bfa",
  },
});
